### ISSUE TITLE
No console output on applehv

### ISSUE THREAD

**Issue by cdrage** [osbuild/bootc-image-builder#105]
Containerfile:

```
FROM quay.io/centos-bootc/fedora-bootc:eln
RUN echo "root:root" | chpasswd
```

Then build using bootc-image-builder with ami selected.

vfkit command:

```
vfkit --cpus 2 --memory 2048 \
    --bootloader efi,variable-store=./efi-variable-store,create \
    --device virtio-blk,path=/Users/cdrage/bootc/image/disk.raw \
    --device virtio-serial,stdio \
    --device virtio-net,nat,mac=72:20:43:d4:38:62 \
    --device virtio-rng \
    --device virtio-input,keyboard \
    --device virtio-input,pointing \
    --device virtio-gpu,width=1920,height=1080 \
    --gui
```

Output when trying to boot:

<img width="403" alt="Screenshot 2024-01-10 at 2 38 59 PM" src="https://github.com/osbuild/bootc-image-builder/assets/6422176/e7d468a0-98c0-4df7-b7f8-4d08c4d4aaf2">

It'll boot, but show the EFI_RNG_PROTOCOL unavailable you have to press enter on.

**Comment by cdrage** [comment]
HOWEVER. This works if you:

1. Create the qcow2 image
2. Convert it with qemu-img: `qemu-img convert -f qcow2 -O raw <path> <image>.img`

**Comment by cgwalters** [comment]
Yeah there's a couple of overlapping things here.  One is today this project incorrectly [hardcodes console kernel arguments](https://github.com/osbuild/bootc-image-builder/blob/47ac7a692ddd8a6c7c99f0d14e637615f0c8f2d5/bib/cmd/bootc-image-builder/image.go#L98).

Now, this topic is quite complex as the knowledge of which `console=` kargs to use is in the general case specific to the matrix of (OS, version, architecture, target platform) where "target platform" here would be like how we treat `ignition.platform.id` in CoreOS derivatives.  (It's not just e.g. "qcow2", because it can be different between openstack and "generic qemu" in the general case).  See https://github.com/coreos/fedora-coreos-config/blob/testing-devel/platforms.yaml for that matrix (which has OS+version implicitly).

The bootc install karg support doesn't directly handle architecture conditionals, we'd need to template our base args...this is a different related bug in https://github.com/CentOS/centos-bootc-layered/blob/main/cloud/usr/lib/bootc/install/05-cloud-kargs.toml

Arguably this should all move to the base image...especially since our default target is servers.  It's just really desktop systems that typically want to disable the serial console by default.

**Comment by cdrage** [comment]
I am no longer experiencing this since I have switched to console commands that will output it correctly, see: https://github.com/containers/podman-desktop-extension-bootc/blob/main/docs/vm_guide.md#arm64-qemu
