### ISSUE TITLE
Unable to install from generated ISO

### ISSUE THREAD

**Issue by noelmiller** [osbuild/bootc-image-builder#114]
Hey Folks! 

Really appreciate all the work going into this project! I was testing the new ISO feature implemented today and I am running into issues booting from the ISO it creates. I have tried 2 different images from https://github.com/ublue-os/ project. 

The first one is Bluefin, which is our Developer Focused build. The other one is Ucore which is some modifications we make on top of traditional CoreOS. Neither seem to boot.

Here are the commands I am using to both generate and test the ISO: 

**Building ISO**
```
sudo podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/output:/output \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --type iso \
    ghcr.io/ublue-os/bluefin:latest
```
**Testing ISO**
```
qemu-img create -f qcow2 disk.qcow2 50G
sudo qemu-system-x86_64 \
    -enable-kvm \
    -cpu host \
    -m 8G \
    -device virtio-net-pci,netdev=n0,mac="FE:0B:6E:22:3D:13" \
    -netdev user,id=n0,net=10.0.2.0/24,hostfwd=tcp::2222-:22 \
    -bios /usr/share/edk2/ovmf/OVMF.inteltdx.fd \
    -cdrom ./output/bootiso/install.iso \
    -drive file=./disk.qcow2
```

Here is some screenshots of where the issue is happening during installation:
![image](https://github.com/osbuild/bootc-image-builder/assets/4983138/0868799e-52bc-4795-823d-91289b9af4d6)

![image](https://github.com/osbuild/bootc-image-builder/assets/4983138/2ad1af33-0c9c-4ed5-adb9-c3e7b0f89f13)

To collect Anaconda logs, I have selected no to the prompt, go into debug shell and then used TMUX to switch to tty2.
I have attached a log of what output I'm receiving during build time and my anaconda logs in the attached `logs.tar.gz` file.

[logs.tar.gz](https://github.com/osbuild/bootc-image-builder/files/13908557/logs.tar.gz)

Let me know if there is anything else you want me to test! 

Thanks, 

Noel

**Comment by ondrejbudai** [comment]
Note that the big difference is that ucore has `bootupd`, whereas bluefin doesn't have it. Noel actually attached logs for bluefin, so this is the non-bootupd path. I haven't investigated what's wrong there.

I investigated `ucore:stable`, though, and the issue is that ucore has bootupd-0.12.12, but anaconda requires 0.12.14 (because it uses `--write-uuid` and `--auto`).

The `testing` branch of `ucore` has 0.12.17, though, so it's just a matter of time:

```
podman run --pull=newer --rm -it ghcr.io/ublue-os/ucore:testing rpm -q bootupd
bootupd-0.2.17-2.fc39.x86_64
```

@noelmiller Feel free to retest with the testing branch, it should work (I ran out of time for today).
