### ISSUE TITLE
Buildroot requires `x86_64-v3`

### ISSUE THREAD

**Issue by supakeen** [osbuild/bootc-image-builder#122]
So ELN, which is our buildroot, is compiled for `x86_64-v3` (see [here](https://developers.redhat.com/articles/2024/01/02/exploring-x86-64-v3-red-hat-enterprise-linux-10)). People are running into issues regularly where they're running `bootc-image-builder` on older Xeon hardware that do not support this level of the architecture. 

It's probably a good idea to error out much earlier if the sublevel is not supported.

We can use the output of `ld.so --help` for this.

**Comment by cgwalters** [comment]
This also touches on https://github.com/osbuild/bootc-image-builder/issues/18 because if our very first step is to fetch the target image and execute it (say running `true` as a sanity check), we will fail at least pretty early on.

IOW we don't need a "buildroot" if the target container is the installer, which compresses complexity here.

Now...there's also the whole larger question of *which base image* this project uses.  I would say that from now, we should use UBI9.  But going forward we'll almost certainly need to support being based on multiple distribution/OS bases too (a lot of things here around tie-in to the build process of different OSes/distributions).

**Comment by cgwalters** [comment]
I think this is fixed by https://github.com/osbuild/bootc-image-builder/pull/138
