### ISSUE TITLE
`cp: failed to preserve ownership for` in Podman Desktop on Mac

### ISSUE THREAD

**Issue by ondrejbudai** [osbuild/bootc-image-builder#14]
@teg reported that the build failed for him when running the build on M1 Mac:

```
⏱  Duration: 32s
cp: failed to preserve ownership for '/output/qcow2/./disk.qcow2': Operation not permitted
cp: failed to preserve ownership for '/output/qcow2/.': Operation not permitted
Traceback (most recent call last):
  File "/usr/bin/osbuild", line 33, in <module>
    sys.exit(load_entry_point('osbuild==101', 'console_scripts', 'osbuild')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/osbuild/main_cli.py", line 179, in osbuild_cli
    export(pid, output_directory, object_store, manifest)
  File "/usr/lib/python3.12/site-packages/osbuild/main_cli.py", line 56, in export
    obj.export(dest)
  File "/usr/lib/python3.12/site-packages/osbuild/objectstore.py", line 249, in export
    subprocess.run(
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cp', '--reflink=auto', '-a', '/store/stage/uuid-c6ab67ad31ed40abae8922411cadb303/data/tree/.', '/output/qcow2']' returned non-zero exit status 1.
running osbuild failed: exit status 1
teg@MacBook-Pro osbuild-deploy-container % 
```

**Comment by mvo5** [comment]
I ran into this too when writing the macos integration test. It can be worked around via setting up the `podman machine` in specific ways, see  https://github.com/osbuild/bootc-image-builder/pull/33/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR96  - I do think we need to talk to the podman team though and see if there is a better fix, it's a peculiar setup. There is also the option to use `podman cp` to/from the machine to push config, pull generated image. The issues seem to be all triggered because of the shared folder between macOS and the linux VM.

**Comment by teg** [comment]
Also worth noting: the build didn't actually fail, just changing the permissions did. An option might be to simply not do that.

**Comment by teg** [comment]
/permissions/ownership/

**Comment by achilleas-k** [comment]
I wonder if we can work around this internally.  I think we can have `bootc-image-builder` output the artifact to a temporary location and then copy it over to the output directory without trying to preserve ownership.  It will double the copy time at the end of the build, which might be a bit long for the (uncompressed) AMI in particular, but I think it would be a smoother experience than having extra steps involving copying things around inside the container itself.

**Comment by achilleas-k** [comment]
Testing this solution now.
