### ISSUE TITLE
odc fails on Fedora 38 and Centos Stream 9 images

### ISSUE THREAD

**Issue by runcom** [osbuild/bootc-image-builder#20]
Trying with the image in $title doesn't yield a working qcow2 - it just hangs in emergency shell where you can't even login as the root account is locked. No user added or nothing, it just doesn't get to a working prompt.

**Comment by mvo5** [comment]
We suspect that this happens because of /boot not being populated because of ostree stuff

**Comment by mvo5** [comment]
A short update on this one. The resulting image fails to mount the `/boot` partition during boot at the `fsck` service in systemd. There is a warning: `/dev/sda3 has unsupported feature(s): FEATURE_C12` [0] and it says: `e2fsck: Get a newer version of e2fsck`. Version `1.47.0` uses FEATURE_C12 by default [1] and we use that in our buildroot with mke2fs. However in the `stream9` container we only have e2fsprogs `1.46.5`. 

We can easily workaround this by doing: `mkfs.ext4 -O ^orphan_file` when creating the filesystems.

[0] https://github.com/tytso/e2fsprogs/blob/master/doc/RelNotes/v1.47.0.txt
[1] https://github.com/tytso/e2fsprogs/issues/147

**Comment by ondrejbudai** [comment]
Should we use Centos Stream 9 buildroot for building Centos Stream 9? Alternatively, we can use the container itself as a buildroot (this is how `bootc install` works).

**Comment by mvo5** [comment]
We just had a chat about this and the agreement is to look into using the container itself as the buildroot and not constructing it from RPMs. This means that for the stream9 container we would use quay.io/centos-bootc/centos-bootc-dev as buildroot (we need this version because the version of ostree in the stream9 container is too old afaict) and for fedora quay.io/centos-bootc/fedora-bootc (or -dev if needed).

**Comment by ondrejbudai** [comment]
github got confused, this is not fixed yet.

**Comment by cgwalters** [comment]
This is fixed now by https://github.com/osbuild/bootc-image-builder/pull/138
