### ISSUE TITLE
Can't build CS9 aarch64 AMI image on x86_64 machine

### ISSUE THREAD

**Issue by henrywang** [osbuild/bootc-image-builder#207]
Build CS9 aarch64 AMI image on x86_64 machine with command
 `sudo podman run --rm -it --privileged --pull=newer --security-opt label=type:unconfined_t --env AWS_ACCESS_KEY_ID=zzz --env AWS_SECRET_ACCESS_KEY=zzz [quay.io/centos-bootc/bootc-image-builder:latest](http://quay.io/centos-bootc/bootc-image-builder:latest) --type ami --aws-ami-name bootc-bib-centos-stream-9-aarch64-v7vu --aws-bucket yyy --aws-region us-east-1 [quay.io/rhel-edge/centos-bootc-test:v7vu](http://quay.io/rhel-edge/centos-bootc-test:v7vu)`

I got the following error:
```
ostree container image deploy --imgref=ostree-unverified-image:dir:/tmp/tmpekdnamgc/image --stateroot=default --target-imgref=ostree-unverified-registry:quay.io/rhel-edge/centos-bootc-test:v7vu --karg=rw --karg=console=tty0 --karg=console=ttyS0 --karg=root=LABEL=root --sysroot=/run/osbuild/tree
error: Performing deployment: Full sync: During fsfreeze-thaw: ioctl(FIFREEZE): Inappropriate ioctl for device
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 140, in <module>
    r = main(stage_args["tree"],
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 135, in main
    ostree_container_deploy(tree, inputs, osname, target_imgref, kopts)
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 109, in ostree_container_deploy
    ostree.cli("container", "image", "deploy",
  File "/run/osbuild/lib/osbuild/util/ostree.py", line 204, in cli
    return subprocess.run(["ostree"] + args,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ostree', 'container', 'image', 'deploy', '--imgref=ostree-unverified-image:dir:/tmp/tmpekdnamgc/image', '--stateroot=default', '--target-imgref=ostree-unverified-registry:quay.io/rhel-edge/centos-bootc-test:v7vu', '--karg=rw', '--karg=console=tty0', '--karg=console=ttyS0', '--karg=root=LABEL=root', '--sysroot=/run/osbuild/tree']' returned non-zero exit status 1.
```

**Comment by henrywang** [comment]
And I added `--platform linux/arm64` in `podman run`. And I got another error `bwrap: Creating new namespace failed: Invalid argument`

**Comment by henrywang** [comment]
I added `--target-arch=aarch64` . Still have `error: Performing deployment: Full sync: During fsfreeze-thaw: ioctl(FIFREEZE): Inappropriate ioctl for device.`

**Comment by mvo5** [comment]
I can reproduce this locally, when I strace it I see:
```
 139463 ?        Sl     0:17  |   |                               \_ /usr/libexec/qemu-binfmt/aarch64-binfmt-P /usr/libexec/libostree/ext/ostree-container /usr/libexec/libostree/ext/ostree-container container image deploy --imgref=ostree-unverified-image:dir:/tmp/tmp0qlkgwjw/image --stateroot=default --target-imgref=ostree-unverified-registry:quay.io/rhel-edge/centos-bootc-test:v7vu --karg=rw --karg=console=tty0 --karg=console=ttyS0 --karg=root=LABEL=root --sysroot=/run/osbuild/tree
...
[pid 139463] ioctl(2, TCGETS <unfinished ...>
...
[pid 139463] <... ioctl resumed>, 0x7ffff20c5560) = -1 ENOTTY (Inappropriate ioctl for device)
```
which looks like it comes from https://github.com/ostreedev/ostree/blob/main/src/libostree/ostree-sysroot-deploy.c#L1668 - given that this runs via aarch64-binfmt-P the strace output must be taken with a grain of salt and it could be that qemu-user is not DTRT with the ioctl(FIFREEZE) (but that is a bit of conjecture at this point)

**Comment by mvo5** [comment]
So, here is my current theory. The container in question is a `aarch64` only container. The cross architecture support is currently assuming that it can fetch a corresponding "native" architecture container which is not the case here. It seems the issue is that bib is doing a:
```go
resolverNative := container.NewResolver(hostArch.String())
...
		for _, c := range sourceSpecs {
			resolver.Add(c)
		}
		containerSpecs[plName], err = resolver.Finish()
```
but there is no error if the container is not for the requested architecture? Which indicates an issue in the `images/pkg/container` library. 

Fwiw, it would be nice if qemu-user could run the build stage in full emulation as well but that is beyond the scope of what the `--target-arch` was designed and tested for. In this case here I think bib must provide a useful error and report that the native arch container is missing. It's probably worthwhile to see if `bootc install to-filesystem` will show the same error or if by some magic this goes away and it works in full emulation mode even for the buildroot.

(I hope the above makes sense, it's a bit terse maybe)

**Comment by mvo5** [comment]
I think we need something like:
```go
diff --git a/pkg/container/client.go b/pkg/container/client.go
index 4ec66d5ba..518cb87c2 100644
--- a/pkg/container/client.go
+++ b/pkg/container/client.go
@@ -397,6 +397,21 @@ func (cl *Client) GetManifest(ctx context.Context, digest digest.Digest, contain
                return
        }
 
+       img, err := ref.NewImage(ctx, cl.sysCtx)
+       if err != nil {
+               return r, err
+       }
+       defer img.Close()
+
+       info, err := img.Inspect(ctx)
+       if err != nil {
+               return r, err
+       }
+       wantArch := cl.sysCtx.ArchitectureChoice
+       if wantArch != "" && (wantArch != info.Architecture) {
+               return r, fmt.Errorf("cannot use image %v: architecture mismatch %v != %v", digest, wantArch, info.Architecture)
+       }
+
        src, err := ref.NewImageSource(ctx, cl.sysCtx)
        if err != nil {
                return
```
right now the resolve code sems to be a bit too loose when it comes to arches :)

**Comment by mvo5** [comment]
It turns out the root cause is that qemu-user does not implement `FIFREEZE` and `FITHAW,`. The attached patch fixes this problem. 

[0001-linux-user-Add-FIFREEZE-and-FITHAW-ioctls.patch.txt](https://github.com/osbuild/bootc-image-builder/files/14343141/0001-linux-user-Add-FIFREEZE-and-FITHAW-ioctls.patch.txt)

I will see how to sent it to upstream

**Comment by cdrage** [comment]
@mvo5 I'm actually getting the same issue too, but the opposite way... building an amd64 on arm64 and then using bootc-image-builder.

If I do the following commands:

```
podman build --platform=linux/amd64 -t quay.io/podai/test:amd64 .
```

And then build the image:

```
podman run \
    --rm \
    -it \
    --privileged \
    --pull=newer \
    --security-opt label=type:unconfined_t \
    -v $(pwd)/bootc:/output \
    quay.io/centos-bootc/bootc-image-builder:latest \
    --target-arch amd64 \
    --type qcow2 \
    quay.io/podai/test:amd6
```

In the output I am getting this warning:
```
time="2024-02-20T15:25:57Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
time="2024-02-20T15:25:57Z" level=info msg="Image operating system mismatch: image uses OS \"linux\"+architecture \"amd64\"+\"\", expecting one of \"linux+arm64+\\\"v8\\\", linux+arm64+\\\"\\\"\""
Getting image source signatures
```

Which is normal.

And then the same error as @henrywang :


```
ostree container image deploy --imgref=ostree-unverified-image:dir:/tmp/tmp4aafiu0p/image --stateroot=default --target-imgref=ostree-unverified-registry:quay.io/podai/test:amd64 --karg=rw --karg=console=tty0 --karg=console=ttyS0 --karg=root=LABEL=root --sysroot=/run/osbuild/tree
error: Performing deployment: Full sync: During fsfreeze-thaw: ioctl(FIFREEZE): Inappropriate ioctl for device
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 140, in <module>
    r = main(stage_args["tree"],
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 135, in main
    ostree_container_deploy(tree, inputs, osname, target_imgref, kopts)
  File "/run/osbuild/bin/org.osbuild.ostree.deploy.container", line 109, in ostree_container_deploy
    ostree.cli("container", "image", "deploy",
  File "/run/osbuild/lib/osbuild/util/ostree.py", line 204, in cli
    return subprocess.run(["ostree"] + args,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ostree', 'container', 'image', 'deploy', '--imgref=ostree-unverified-image:dir:/tmp/tmp4aafiu0p/image', '--stateroot=default', '--target-imgref=ostree-unverified-registry:quay.io/podai/test:amd64', '--karg=rw', '--karg=console=tty0', '--karg=console=ttyS0', '--karg=root=LABEL=root', '--sysroot=/run/osbuild/tree']' returned non-zero exit status 1.

⏱  Duration: 64s

Failed
Error: running osbuild failed: exit status 1
2024/02/20 15:27:32 error: running osbuild failed: exit status 1
```

**Comment by mvo5** [comment]
@cdrage I'm 95% certain that my qemu patch will also fix your case. Maybe someone from the qemu folks we know can have a look and we could backport it into fedora/centos?

**Comment by mvo5** [comment]
Actually sandbox support for binfmt_misc landed recently (c.f. https://git.kernel.org/pub/scm/linux/kernel/git/vfs/vfs.git/commit/?h=vfs.binfmt_misc&id=ecddcab2d1b15fea782889237093bd069979c8c7 - since 6.8-rc5 it seems).

**Comment by ericcurtin** [comment]
Hit a very similar issue when doing a cross-build environment (building for aarch64 on x86_64) using podman in Automotive:

```
git clone https://gitlab.com/CentOS/automotive/sample-images.git
sudo podman run --arch aarch64 -v $PWD:$PWD --rm --privileged --pull=newer --security-opt label=type:unconfined_t quay.io/centos-sig-automotive/automotive-osbuild /bin/bash -c "cd $PWD/sample-images/osbuild-manifests/; make cs9-qemu-minimal-ostree.aarch64.qcow2"
```

```
bwrap: Creating new namespace failed: Invalid argument

⏱  Duration: 2s

Failed
make: *** [Makefile:172: cs9-qemu-minimal-ostree.aarch64.qcow2] Error 1
```

**Comment by mvo5** [comment]
The fixed qemu package got released into fedora recently as https://bodhi.fedoraproject.org/updates/FEDORA-2024-90617acee3

**Comment by ericcurtin** [comment]
Cool! Thanks for letting me know @mvo5 

I was surprised it failed because we had been maintaining a qemu based emulator that this works fine with.

I'd rather we moved to podman + emulator though, it's easier for the users to use podman and let the emulation get set up under the hood automagically.

**Comment by ericcurtin** [comment]
I upgraded to 8.1.3-4.fc39.x86_64, still seem to get the bwrap problem

**Comment by ericcurtin** [comment]
@henrywang you seemed to state that you may have fixed the bwrap issue, how so? Maybe podman 5.0 just fixes these things :shrug:

**Comment by vrothberg** [comment]
Friendly ping, @henrywang.  Are there news on this issue?

**Comment by henrywang** [comment]
I tried build aarch64 AMI image on x86_64 machine. It works now. The qemu version should be `8.1.3-4` which has qemu fix included.

**Comment by mvo5** [comment]
> Hit a similar issue when doing a cross-build environment (building for aarch64 on x86_64) using podman in Automotive (we have a similar project here https://gitlab.com/CentOS/automotive/container-images/automotive-osbuild):
> 
> ```
> git clone https://gitlab.com/CentOS/automotive/sample-images.git
> sudo podman run --arch aarch64 -v $PWD:$PWD --rm --privileged --pull=newer --security-opt label=type:unconfined_t quay.io/centos-sig-automotive/automotive-osbuild /bin/bash -c "cd $PWD/sample-images/osbuild-manifests/; make cs9-qemu-minimal-ostree.aarch64.qcow2"
> ```
> 
> ```
> bwrap: Creating new namespace failed: Invalid argument
> 
> ⏱  Duration: 2s
> 
> Failed
> make: *** [Makefile:172: cs9-qemu-minimal-ostree.aarch64.qcow2] Error 1
> ```

Hey, thanks for raising this and sorry for my slow reply. I only now realized that this involved using a different git repository and with that I was able to reproduce the issue.

I had a look and the issue is that bwrap seems to use something that qemu-user does not yet support. I tried to debug it but couldn't not see right away which syscall is not supported (but also did not spend too much time on it).

I don't really know much about the above repository but if you can arrange it so that bwrap is run with your native arch and you only fetch the container/buildroot in the non-native arch, then this should work (this is what bib is doing).

If it's an important use-case for you I can look again and spend more time debugging bwrap, a casual strace was not enough to reveal the underlying missing syscall.

**Comment by ondrejbudai** [comment]
I think that @henrywang's issue was resolved. I agree that @ericcurtin's issue is kinda similar, but since bootc-image-builder isn't involved at all, I will close this issue. Please, feel free to open a new one in osbuild/osbuild and link this one from there. Apologizes for creating more tickets, but I'm trying to keep the issue trackers clean.
